Repository CycloneDX/cyclonedx-javascript-library, pull requests merged in 2023-05, with the labels that each got.

#721 feat: base-serializer runs bomRefDiscrimination on vulnerabilities
  src/serialize/baseSerializer.ts
Labels: enhancement

#548 feat: `bom.vulnerabilities` JSON normalization
  src/enums/vulnerability/severity.ts
  src/models/vulnerability/advisory.ts
  src/models/vulnerability/affect.ts
  src/models/vulnerability/rating.ts
  src/models/vulnerability/reference.ts
  src/models/vulnerability/source.ts
  src/models/vulnerability/vulnerability.ts
  src/serialize/json/normalize.ts
  src/serialize/json/types.ts
  src/spec.ts
  tests/_data/models.js
  tests/_data/normalizeResults/json_sortedLists_spec1.4.json
  tests/_data/serializeResults/json_complex_spec1.4.json.bin
  tests/unit/Models.Vulnerability.Vulnerability.spec.js
Labels: breaking change

#724 fix
  src/serialize/json/normalize.ts
  tests/_data/normalizeResults/json_sortedLists_spec1.4.json
  tests/_data/serializeResults/json_complex_spec1.4.json.bin
Labels: bug

#722 feat: serialize/normalizer `bom.vulnerabilities`
  HISTORY.md
  README.md
  package.json
  src/_helpers/sortable.ts
  src/enums/index.ts
  src/enums/vulnerability/affectStatus.ts
  src/enums/vulnerability/analysisJustification.ts
  src/enums/vulnerability/analysisResponse.ts
  src/enums/vulnerability/analysisState.ts
  src/enums/vulnerability/ratingMethod.ts
  src/enums/vulnerability/severity.ts
  src/models/index.ts
  src/models/vulnerability/advisory.ts
  src/models/vulnerability/affect.ts
  src/models/vulnerability/analysis.ts
  src/models/vulnerability/credits.ts
  src/models/vulnerability/rating.ts
  src/models/vulnerability/reference.ts
  src/models/vulnerability/source.ts
  src/models/vulnerability/vulnerability.ts
  src/serialize/baseSerializer.ts
  src/serialize/bomRefDiscriminator.ts
  src/serialize/json/normalize.ts
  src/serialize/json/types.ts
  src/serialize/xml/normalize.ts
  src/spec.ts
  src/types/cwe.ts
  tests/_data/models.js
  tests/_data/normalizeResults/json_sortedLists_spec1.2.json
  tests/_data/normalizeResults/json_sortedLists_spec1.3.json
  tests/_data/normalizeResults/json_sortedLists_spec1.4.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
  tests/_data/serializeResults/json_complex_spec1.2.json.bin
  tests/_data/serializeResults/json_complex_spec1.3.json.bin
  tests/_data/serializeResults/json_complex_spec1.4.json.bin
  tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
  tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
  tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
  tests/unit/Models.Vulnerability.Vulnerability.spec.js
Labels: enhancement, breaking change

#748 docs: fix history
  HISTORY.md
Labels: documentation

#752 remove deprecated symbols
  HISTORY.md
  src/builders/index.node.ts
  src/factories/index.node.ts
  src/models/hash.ts
  src/serialize/json/normalize.ts
  src/serialize/xml/normalize.ts
  src/types/index.ts
  src/types/urn.ts
  src/utils/bomUtility.ts
Labels: breaking change

#753 models `ComponentEvidence`
  HISTORY.md
  README.md
  src/models/attachment.ts
  src/models/component.ts
  src/serialize/json/normalize.ts
  src/serialize/json/types.ts
  src/serialize/xml/normalize.ts
  src/spec.ts
  tests/_data/models.js
  tests/_data/normalizeResults/json_sortedLists_spec1.2.json
  tests/_data/normalizeResults/json_sortedLists_spec1.3.json
  tests/_data/normalizeResults/json_sortedLists_spec1.4.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.2.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.3.json
  tests/_data/normalizeResults/xml_sortedLists_spec1.4.json
  tests/_data/serializeResults/json_complex_spec1.2.json.bin
  tests/_data/serializeResults/json_complex_spec1.3.json.bin
  tests/_data/serializeResults/json_complex_spec1.4.json.bin
  tests/_data/serializeResults/xml_complex_spec1.2.xml.bin
  tests/_data/serializeResults/xml_complex_spec1.3.xml.bin
  tests/_data/serializeResults/xml_complex_spec1.4.xml.bin
Labels: enhancement

#769 docs: add `LicenseFactory` to the examples
  examples/node-javascript/example.cjs
  examples/node-javascript/example.mjs
  examples/node-typescript/example.cjs/src/example.ts
  examples/node-typescript/example.mjs/src/example.ts
  examples/web/example.html
Labels: documentation
